# Server
server:
    port: 8761

# Application
spring:
    application:
        name: eureka-server

#Eureka-Server
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false