# Server Config
server:
    port: ${PORT:0}

# Eureka Config
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Application Config
spring:
    application:
        name: ms-credit-evaluator

# Management Config
management:
    endpoints:
        web:
            exposure:
                include: '*'